services:
  - type: web
    name: involex-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: involex-postgres
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # Will be set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"  # Will be updated with extension ID after Chrome store

databases:
  - name: involex-postgres
    plan: free
    databaseName: involex
    user: involex_user
